// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSYHU7iWw7tYmlQ8b1aA6jnrWjquzJ3RY',
    appId: '1:941674630786:web:9c75c6abc0d50e993b2e9b',
    messagingSenderId: '941674630786',
    projectId: 'cargoflow-b9fc3',
    authDomain: 'cargoflow-b9fc3.firebaseapp.com',
    storageBucket: 'cargoflow-b9fc3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD06tl4Apv_wlB_EznVN0RrlrI8NAtEdLo',
    appId: '1:941674630786:android:b3be41339cbe88c13b2e9b',
    messagingSenderId: '941674630786',
    projectId: 'cargoflow-b9fc3',
    storageBucket: 'cargoflow-b9fc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8WbPa-MA9zIPgBRDbS65YDzXAgiNc9Ng',
    appId: '1:941674630786:ios:8b431e52e38b5af13b2e9b',
    messagingSenderId: '941674630786',
    projectId: 'cargoflow-b9fc3',
    storageBucket: 'cargoflow-b9fc3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8WbPa-MA9zIPgBRDbS65YDzXAgiNc9Ng',
    appId: '1:941674630786:ios:8b431e52e38b5af13b2e9b',
    messagingSenderId: '941674630786',
    projectId: 'cargoflow-b9fc3',
    storageBucket: 'cargoflow-b9fc3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSYHU7iWw7tYmlQ8b1aA6jnrWjquzJ3RY',
    appId: '1:941674630786:web:c031a75594b31a9a3b2e9b',
    messagingSenderId: '941674630786',
    projectId: 'cargoflow-b9fc3',
    authDomain: 'cargoflow-b9fc3.firebaseapp.com',
    storageBucket: 'cargoflow-b9fc3.firebasestorage.app',
  );
}
